<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="12" passed="6" failed="5" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-04-27T08:03:18 PDT" name="TutorialsNinja Automation Suite" finished-at="2023-04-27T08:04:33 PDT" duration-ms="74916">
    <groups>
    </groups>
    <test started-at="2023-04-27T08:03:18 PDT" name="TutorialsNinja Tests" finished-at="2023-04-27T08:04:33 PDT" duration-ms="74916">
      <class name="com.ninja.qa.testcases.LoginTest">
        <test-method signature="verifyNinjaLoginWithValideUsernameAndPassword(java.lang.String,java.lang.String)[pri:1, instance:com.ninja.qa.testcases.LoginTest@7fd50002]" started-at="2023-04-27T08:03:56 PDT" name="verifyNinjaLoginWithValideUsernameAndPassword" data-provider="tutorialsninjaExelDataProvider" finished-at="2023-04-27T08:03:56 PDT" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.poi.xssf.usermodel.XSSFSheet.getLastRowNum()" because "com.ninja.qa.test.data.SupplyTestData.sheet" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "org.apache.poi.xssf.usermodel.XSSFSheet.getLastRowNum()" because "com.ninja.qa.test.data.SupplyTestData.sheet" is null
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:50)
at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:146)
at org.testng.internal.Parameters.handleParameters(Parameters.java:798)
at org.testng.internal.Parameters.handleParameters(Parameters.java:740)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:791)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.NullPointerException: Cannot invoke "org.apache.poi.xssf.usermodel.XSSFSheet.getLastRowNum()" because "com.ninja.qa.test.data.SupplyTestData.sheet" is null
at com.ninja.qa.test.data.SupplyTestData.getTutorialsninjaTestDataFromExcelSheet(SupplyTestData.java:35)
at com.ninja.qa.test.data.SupplyTestData.excelSheetDataSuplier(SupplyTestData.java:25)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:77)
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:46)
... 25 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyNinjaLoginWithValideUsernameAndPassword -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.ninja.qa.testcases.LoginTest@7fd50002]" started-at="2023-04-27T08:03:56 PDT" name="setUp" finished-at="2023-04-27T08:04:02 PDT" duration-ms="5909" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyNinjaLoginWithInvalideUsernameAndPassword()[pri:2, instance:com.ninja.qa.testcases.LoginTest@7fd50002]" started-at="2023-04-27T08:04:02 PDT" name="verifyNinjaLoginWithInvalideUsernameAndPassword" finished-at="2023-04-27T08:04:02 PDT" duration-ms="186" status="FAIL">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Keys to send should be a not null CharSequence]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Keys to send should be a not null CharSequence
at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:98)
at com.ninja.qa.testcases.LoginTest.verifyNinjaLoginWithInvalideUsernameAndPassword(LoginTest.java:53)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyNinjaLoginWithInvalideUsernameAndPassword -->
        <test-method is-config="true" signature="quite()[pri:0, instance:com.ninja.qa.testcases.LoginTest@7fd50002]" started-at="2023-04-27T08:04:02 PDT" name="quite" finished-at="2023-04-27T08:04:02 PDT" duration-ms="304" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quite -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.ninja.qa.testcases.LoginTest@7fd50002]" started-at="2023-04-27T08:04:02 PDT" name="setUp" finished-at="2023-04-27T08:04:06 PDT" duration-ms="4197" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyNinjaLoginWithValideUsernameAndInvalidePassword()[pri:3, instance:com.ninja.qa.testcases.LoginTest@7fd50002]" started-at="2023-04-27T08:04:06 PDT" name="verifyNinjaLoginWithValideUsernameAndInvalidePassword" finished-at="2023-04-27T08:04:07 PDT" duration-ms="665" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "java.lang.CharSequence.toString()" because "s" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.toString()" because "s" is null
at java.base/java.lang.String.contains(String.java:2854)
at com.ninja.qa.testcases.LoginTest.verifyNinjaLoginWithValideUsernameAndInvalidePassword(LoginTest.java:72)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyNinjaLoginWithValideUsernameAndInvalidePassword -->
        <test-method is-config="true" signature="quite()[pri:0, instance:com.ninja.qa.testcases.LoginTest@7fd50002]" started-at="2023-04-27T08:04:07 PDT" name="quite" finished-at="2023-04-27T08:04:07 PDT" duration-ms="327" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quite -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.ninja.qa.testcases.LoginTest@7fd50002]" started-at="2023-04-27T08:04:07 PDT" name="setUp" finished-at="2023-04-27T08:04:12 PDT" duration-ms="4102" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyNinjaLoginWithEmptyUsernameAndCorrectPassword()[pri:4, instance:com.ninja.qa.testcases.LoginTest@7fd50002]" started-at="2023-04-27T08:04:12 PDT" name="verifyNinjaLoginWithEmptyUsernameAndCorrectPassword" finished-at="2023-04-27T08:04:12 PDT" duration-ms="581" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "java.lang.CharSequence.toString()" because "s" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.toString()" because "s" is null
at java.base/java.lang.String.contains(String.java:2854)
at com.ninja.qa.testcases.LoginTest.verifyNinjaLoginWithEmptyUsernameAndCorrectPassword(LoginTest.java:84)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyNinjaLoginWithEmptyUsernameAndCorrectPassword -->
        <test-method is-config="true" signature="quite()[pri:0, instance:com.ninja.qa.testcases.LoginTest@7fd50002]" started-at="2023-04-27T08:04:12 PDT" name="quite" finished-at="2023-04-27T08:04:12 PDT" duration-ms="322" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quite -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.ninja.qa.testcases.LoginTest@7fd50002]" started-at="2023-04-27T08:04:12 PDT" name="setUp" finished-at="2023-04-27T08:04:17 PDT" duration-ms="4219" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyNinjaLoginWithValideUsernameAndEmptyPassword()[pri:5, instance:com.ninja.qa.testcases.LoginTest@7fd50002]" started-at="2023-04-27T08:04:17 PDT" name="verifyNinjaLoginWithValideUsernameAndEmptyPassword" finished-at="2023-04-27T08:04:17 PDT" duration-ms="663" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyNinjaLoginWithValideUsernameAndEmptyPassword -->
        <test-method is-config="true" signature="quite()[pri:0, instance:com.ninja.qa.testcases.LoginTest@7fd50002]" started-at="2023-04-27T08:04:17 PDT" name="quite" finished-at="2023-04-27T08:04:18 PDT" duration-ms="298" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quite -->
      </class> <!-- com.ninja.qa.testcases.LoginTest -->
      <class name="com.ninja.qa.testcases.CreatAcountTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.ninja.qa.testcases.CreatAcountTest@5e2c3d18]" started-at="2023-04-27T08:03:18 PDT" name="setUp" finished-at="2023-04-27T08:03:27 PDT" duration-ms="8764" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyNinjaRegesterWithValideUsernameAndPassword()[pri:1, instance:com.ninja.qa.testcases.CreatAcountTest@5e2c3d18]" started-at="2023-04-27T08:03:27 PDT" name="verifyNinjaRegesterWithValideUsernameAndPassword" finished-at="2023-04-27T08:03:29 PDT" duration-ms="1871" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyNinjaRegesterWithValideUsernameAndPassword -->
        <test-method is-config="true" signature="quite()[pri:0, instance:com.ninja.qa.testcases.CreatAcountTest@5e2c3d18]" started-at="2023-04-27T08:03:29 PDT" name="quite" finished-at="2023-04-27T08:03:29 PDT" duration-ms="380" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quite -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.ninja.qa.testcases.CreatAcountTest@5e2c3d18]" started-at="2023-04-27T08:03:29 PDT" name="setUp" finished-at="2023-04-27T08:03:36 PDT" duration-ms="6628" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="VerifyRegisteringanAccountbyprovidingallthefields()[pri:2, instance:com.ninja.qa.testcases.CreatAcountTest@5e2c3d18]" started-at="2023-04-27T08:03:36 PDT" name="VerifyRegisteringanAccountbyprovidingallthefields" finished-at="2023-04-27T08:03:38 PDT" duration-ms="1770" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyRegisteringanAccountbyprovidingallthefields -->
        <test-method is-config="true" signature="quite()[pri:0, instance:com.ninja.qa.testcases.CreatAcountTest@5e2c3d18]" started-at="2023-04-27T08:03:38 PDT" name="quite" finished-at="2023-04-27T08:03:38 PDT" duration-ms="315" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quite -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.ninja.qa.testcases.CreatAcountTest@5e2c3d18]" started-at="2023-04-27T08:03:38 PDT" name="setUp" finished-at="2023-04-27T08:03:48 PDT" duration-ms="10014" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="VerifyRegisteringanAccountbyprovidingtheexistingaccount()[pri:3, instance:com.ninja.qa.testcases.CreatAcountTest@5e2c3d18]" started-at="2023-04-27T08:03:48 PDT" name="VerifyRegisteringanAccountbyprovidingtheexistingaccount" finished-at="2023-04-27T08:03:49 PDT" duration-ms="1133" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "java.lang.CharSequence.toString()" because "s" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.toString()" because "s" is null
at java.base/java.lang.String.contains(String.java:2854)
at com.ninja.qa.testcases.CreatAcountTest.VerifyRegisteringanAccountbyprovidingtheexistingaccount(CreatAcountTest.java:86)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyRegisteringanAccountbyprovidingtheexistingaccount -->
        <test-method is-config="true" signature="quite()[pri:0, instance:com.ninja.qa.testcases.CreatAcountTest@5e2c3d18]" started-at="2023-04-27T08:03:49 PDT" name="quite" finished-at="2023-04-27T08:03:50 PDT" duration-ms="323" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quite -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.ninja.qa.testcases.CreatAcountTest@5e2c3d18]" started-at="2023-04-27T08:03:50 PDT" name="setUp" finished-at="2023-04-27T08:03:54 PDT" duration-ms="4833" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="VerifyRegistereingAccountWithoutFillingAnyDetails()[pri:4, instance:com.ninja.qa.testcases.CreatAcountTest@5e2c3d18]" started-at="2023-04-27T08:03:54 PDT" name="VerifyRegistereingAccountWithoutFillingAnyDetails" finished-at="2023-04-27T08:03:55 PDT" duration-ms="482" status="FAIL">
          <exception class="org.openqa.selenium.InvalidSelectorException">
            <message>
              <![CDATA[invalid selector: Unable to locate an element with the xpath expression //div[contains(@class,'alert-dismissible'] because of the following error:
SyntaxError: Failed to execute 'evaluate' on 'Document': The string '//div[contains(@class,'alert-dismissible']' is not a valid XPath expression.
  (Session info: chrome=112.0.5615.138)
For documentation on this error, please visit: https://selenium.dev/exceptions/#invalid_selector_exception
Build info: version: '4.8.3', revision: 'e5e76298c3'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.5'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [040fc0cc7b6a372f698f2316f4117448, findElement {using=xpath, value=//div[contains(@class,'alert-dismissible']}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 112.0.5615.138, chrome: {chromedriverVersion: 112.0.5615.49 (bd2a7bcb881c..., userDataDir: C:\Users\REZIKA~1\AppData\L...}, goog:chromeOptions: {debuggerAddress: localhost:51276}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:51276/devtoo..., se:cdpVersion: 112.0.5615.138, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 040fc0cc7b6a372f698f2316f4117448]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.InvalidSelectorException: invalid selector: Unable to locate an element with the xpath expression //div[contains(@class,'alert-dismissible'] because of the following error:
SyntaxError: Failed to execute 'evaluate' on 'Document': The string '//div[contains(@class,'alert-dismissible']' is not a valid XPath expression.
  (Session info: chrome=112.0.5615.138)
For documentation on this error, please visit: https://selenium.dev/exceptions/#invalid_selector_exception
Build info: version: '4.8.3', revision: 'e5e76298c3'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.5'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [040fc0cc7b6a372f698f2316f4117448, findElement {using=xpath, value=//div[contains(@class,'alert-dismissible']}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 112.0.5615.138, chrome: {chromedriverVersion: 112.0.5615.49 (bd2a7bcb881c..., userDataDir: C:\Users\REZIKA~1\AppData\L...}, goog:chromeOptions: {debuggerAddress: localhost:51276}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:51276/devtoo..., se:cdpVersion: 112.0.5615.138, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 040fc0cc7b6a372f698f2316f4117448
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:193)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:183)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:158)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:162)
at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:60)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:352)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:344)
at com.ninja.qa.testcases.CreatAcountTest.VerifyRegistereingAccountWithoutFillingAnyDetails(CreatAcountTest.java:95)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.InvalidSelectorException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyRegistereingAccountWithoutFillingAnyDetails -->
        <test-method is-config="true" signature="quite()[pri:0, instance:com.ninja.qa.testcases.CreatAcountTest@5e2c3d18]" started-at="2023-04-27T08:03:55 PDT" name="quite" finished-at="2023-04-27T08:03:55 PDT" duration-ms="310" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quite -->
      </class> <!-- com.ninja.qa.testcases.CreatAcountTest -->
      <class name="com.ninja.qa.testcases.Search">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.ninja.qa.testcases.Search@533bda92]" started-at="2023-04-27T08:04:18 PDT" name="setUp" finished-at="2023-04-27T08:04:22 PDT" duration-ms="4303" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="VerifySearchingWithanExistingProductName()[pri:1, instance:com.ninja.qa.testcases.Search@533bda92]" started-at="2023-04-27T08:04:22 PDT" name="VerifySearchingWithanExistingProductName" finished-at="2023-04-27T08:04:23 PDT" duration-ms="738" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifySearchingWithanExistingProductName -->
        <test-method is-config="true" signature="quite()[pri:0, instance:com.ninja.qa.testcases.Search@533bda92]" started-at="2023-04-27T08:04:23 PDT" name="quite" finished-at="2023-04-27T08:04:23 PDT" duration-ms="306" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quite -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.ninja.qa.testcases.Search@533bda92]" started-at="2023-04-27T08:04:23 PDT" name="setUp" finished-at="2023-04-27T08:04:27 PDT" duration-ms="3761" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="VerifysearchingwithanonexistingProductName()[pri:2, instance:com.ninja.qa.testcases.Search@533bda92]" started-at="2023-04-27T08:04:27 PDT" name="VerifysearchingwithanonexistingProductName" finished-at="2023-04-27T08:04:27 PDT" duration-ms="664" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifysearchingwithanonexistingProductName -->
        <test-method is-config="true" signature="quite()[pri:0, instance:com.ninja.qa.testcases.Search@533bda92]" started-at="2023-04-27T08:04:27 PDT" name="quite" finished-at="2023-04-27T08:04:28 PDT" duration-ms="307" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quite -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.ninja.qa.testcases.Search@533bda92]" started-at="2023-04-27T08:04:28 PDT" name="setUp" finished-at="2023-04-27T08:04:32 PDT" duration-ms="4629" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="VerifysearchingwithoutprovidinganyProductName()[pri:3, instance:com.ninja.qa.testcases.Search@533bda92]" started-at="2023-04-27T08:04:32 PDT" name="VerifysearchingwithoutprovidinganyProductName" finished-at="2023-04-27T08:04:33 PDT" duration-ms="557" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifysearchingwithoutprovidinganyProductName -->
        <test-method is-config="true" signature="quite()[pri:0, instance:com.ninja.qa.testcases.Search@533bda92]" started-at="2023-04-27T08:04:33 PDT" name="quite" finished-at="2023-04-27T08:04:33 PDT" duration-ms="334" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quite -->
      </class> <!-- com.ninja.qa.testcases.Search -->
    </test> <!-- TutorialsNinja Tests -->
  </suite> <!-- TutorialsNinja Automation Suite -->
</testng-results>
